# 06.02 — Temporal Features

Create cyclical temporal encodings without modifying the source dataset.

In [1]:
# Import libraries
from pathlib import Path
import sys

In [2]:
# define the root directory of the project
PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / 'src').exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

CONFIG_PATH = PROJECT_ROOT / 'configs' / 'feature_engineering.yaml'
CONFIG_PATH

WindowsPath('e:/jcuenca/OneDrive - GUSCanada/5toTerm/01_Capstone/DataLocal/ontario-electricity-peak-risk/configs/feature_engineering.yaml')

In [3]:
# Import module to manage the Feature Engineering process
from src.ontario_peak_risk.feature_engineering.common import (
    load_feature_config,
    load_clean_dataset,
    ensure_directories,
)

In [4]:
# Config Feature Engineering process and Load the dataset
CONFIG, _ = load_feature_config(CONFIG_PATH)
REPORTS_DIR, DOCS_DIR = ensure_directories(CONFIG, PROJECT_ROOT)
clean_dataset = load_clean_dataset(CONFIG, PROJECT_ROOT)
clean_dataset.shape

(262944, 66)

In [5]:
# Import the functions to run baseline Feature Engineering process and add temporal features
from src.ontario_peak_risk.feature_engineering.base_features import build_base_dataset
from src.ontario_peak_risk.feature_engineering.temporal_features import add_temporal_features

In [6]:
# Run the baseline Feature Engineering process
base_dataset, _ = build_base_dataset(clean_dataset, CONFIG)
temporal_dataset, temporal_dictionary = add_temporal_features(base_dataset, CONFIG)
temporal_dictionary

,feature_name,feature_family,source_columns,description,forecasting_candidate,peak_risk_candidate,computation_scope,leakage_risk
0,hour_sin,temporal_cyclical,hour,Sine cyclical encoding of hour with period 24.,True,True,static_dataset,low
1,hour_cos,temporal_cyclical,hour,Cosine cyclical encoding of hour with period 24.,True,True,static_dataset,low
2,weekday_sin,temporal_cyclical,weekday,Sine cyclical encoding of weekday with period 7.,True,True,static_dataset,low
3,weekday_cos,temporal_cyclical,weekday,Cosine cyclical encoding of weekday with perio...,True,True,static_dataset,low
4,month_sin,temporal_cyclical,month,Sine cyclical encoding of month with period 12.,True,True,static_dataset,low
5,month_cos,temporal_cyclical,month,Cosine cyclical encoding of month with period 12.,True,True,static_dataset,low
6,day_of_year_sin,temporal_cyclical,day_of_year,Sine cyclical encoding of day_of_year with per...,True,True,static_dataset,low
7,day_of_year_cos,temporal_cyclical,day_of_year,Cosine cyclical encoding of day_of_year with p...,True,True,static_dataset,low

In [7]:
# Display the temporal dataset with the new features
temporal_dataset[[c for c in temporal_dataset.columns if c.endswith('_sin') or c.endswith('_cos')]].head()

,hour_sin,hour_cos,weekday_sin,weekday_cos,month_sin,month_cos,day_of_year_sin,day_of_year_cos
0,0.0,1.0,-0.433884,-0.900969,0.5,0.866025,0.017202,0.999852
1,0.258819,0.965926,-0.433884,-0.900969,0.5,0.866025,0.017202,0.999852
2,0.5,0.866025,-0.433884,-0.900969,0.5,0.866025,0.017202,0.999852
3,0.707107,0.707107,-0.433884,-0.900969,0.5,0.866025,0.017202,0.999852
4,0.866025,0.5,-0.433884,-0.900969,0.5,0.866025,0.017202,0.999852

In [8]:
# Display all generated cyclical temporal features
temporal_dictionary[
    temporal_dictionary["feature_family"] == "temporal_cyclical"
]

,feature_name,feature_family,source_columns,description,forecasting_candidate,peak_risk_candidate,computation_scope,leakage_risk
0,hour_sin,temporal_cyclical,hour,Sine cyclical encoding of hour with period 24.,True,True,static_dataset,low
1,hour_cos,temporal_cyclical,hour,Cosine cyclical encoding of hour with period 24.,True,True,static_dataset,low
2,weekday_sin,temporal_cyclical,weekday,Sine cyclical encoding of weekday with period 7.,True,True,static_dataset,low
3,weekday_cos,temporal_cyclical,weekday,Cosine cyclical encoding of weekday with perio...,True,True,static_dataset,low
4,month_sin,temporal_cyclical,month,Sine cyclical encoding of month with period 12.,True,True,static_dataset,low
5,month_cos,temporal_cyclical,month,Cosine cyclical encoding of month with period 12.,True,True,static_dataset,low
6,day_of_year_sin,temporal_cyclical,day_of_year,Sine cyclical encoding of day_of_year with per...,True,True,static_dataset,low
7,day_of_year_cos,temporal_cyclical,day_of_year,Cosine cyclical encoding of day_of_year with p...,True,True,static_dataset,low