# 07.06 — Target Definition Summary

Execute the complete Target Definition Phase workflow and review the final modeling handoff.

In [2]:
# Import libraries
from pathlib import Path
import sys

In [4]:
# Define the root directory of the project
PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / 'src').exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

CONFIG_PATH = PROJECT_ROOT / 'configs' / 'target_definition.yaml'
CONFIG_PATH

WindowsPath('e:/jcuenca/OneDrive - GUSCanada/5toTerm/01_Capstone/Codigo/ontario-electricity-peak-risk/configs/target_definition.yaml')

In [5]:
# Import the run_target_definition function
from src.ontario_peak_risk.target_definition.run_target_definition import run_target_definition

In [7]:
# Run the target definition process and display the results
results = run_target_definition(CONFIG_PATH)
results.keys()

Target Definition Phase completed successfully.
Rows in feature dataset: 262,944
Complete 24-hour forecast origins: 262,800
Outputs: E:\jcuenca\OneDrive - GUSCanada\5toTerm\01_Capstone\Codigo\ontario-electricity-peak-risk\data\processed\target_definition
Reports: E:\jcuenca\OneDrive - GUSCanada\5toTerm\01_Capstone\Codigo\ontario-electricity-peak-risk\reports\target_definition
Documentation: E:\jcuenca\OneDrive - GUSCanada\5toTerm\01_Capstone\Codigo\ontario-electricity-peak-risk\docs\target_definition

dict_keys(['feature_dataset', 'forecast_matrix', 'complete_forecast_matrix', 'forecast_summary', 'peak_labels', 'peak_thresholds', 'peak_distributions', 'alignment_sample', 'forecast_validation', 'peak_validation'])

In [8]:
# Display the forecast summary from the results
results['forecast_summary']

        target  available_count  missing_count  coverage_pct
0   target_h01           262938              6     99.997718
1   target_h02           262932             12     99.995436
2   target_h03           262926             18     99.993154
3   target_h04           262920             24     99.990873
4   target_h05           262914             30     99.988591
5   target_h06           262908             36     99.986309
6   target_h07           262902             42     99.984027
7   target_h08           262896             48     99.981745
8   target_h09           262890             54     99.979463
9   target_h10           262884             60     99.977181
10  target_h11           262878             66     99.974900
11  target_h12           262872             72     99.972618
12  target_h13           262866             78     99.970336
13  target_h14           262860             84     99.968054
14  target_h15           262854             90     99.965772
15  target_h16           262848             96     99.963490
16  target_h17           262842            102     99.961208
17  target_h18           262836            108     99.958927
18  target_h19           262830            114     99.956645
19  target_h20           262824            120     99.954363
20  target_h21           262818            126     99.952081
21  target_h22           262812            132     99.949799
22  target_h23           262806            138     99.947517
23  target_h24           262800            144     99.945235

In [9]:
# Display the peak distributions from the results
results['peak_distributions']['overall']

   observations  peak_hours  peak_rate_pct
0        210384       13784       6.551829

In [10]:
# Display the forecast validation results from the results
results['forecast_validation']

,check,violations,status,description
0,target_origin_row_count,0,PASS,Target matrix must preserve one forecast origi...
1,unique_forecast_origin,0,PASS,FSA + forecast origin must remain unique.
2,alignment_h01,0,PASS,h+1 target must equal observed consumption exa...
3,alignment_h02,0,PASS,h+2 target must equal observed consumption exa...
4,alignment_h03,0,PASS,h+3 target must equal observed consumption exa...
5,alignment_h04,0,PASS,h+4 target must equal observed consumption exa...
6,alignment_h05,0,PASS,h+5 target must equal observed consumption exa...
7,alignment_h06,0,PASS,h+6 target must equal observed consumption exa...
8,alignment_h07,0,PASS,h+7 target must equal observed consumption exa...
9,alignment_h08,0,PASS,h+8 target must equal observed consumption exa...
10,alignment_h09,0,PASS,h+9 target must equal observed consumption exa...
11,alignment_h10,0,PASS,h+10 target must equal observed consumption ex...
12,alignment_h11,0,PASS,h+11 target must equal observed consumption ex...
13,alignment_h12,0,PASS,h+12 target must equal observed consumption ex...
14,alignment_h13,0,PASS,h+13 target must equal observed consumption ex...
15,alignment_h14,0,PASS,h+14 target must equal observed consumption ex...
16,alignment_h15,0,PASS,h+15 target must equal observed consumption ex...
17,alignment_h16,0,PASS,h+16 target must equal observed consumption ex...
18,alignment_h17,0,PASS,h+17 target must equal observed consumption ex...
19,alignment_h18,0,PASS,h+18 target must equal observed consumption ex...
20,alignment_h19,0,PASS,h+19 target must equal observed consumption ex...
21,alignment_h20,0,PASS,h+20 target must equal observed consumption ex...
22,alignment_h21,0,PASS,h+21 target must equal observed consumption ex...
23,alignment_h22,0,PASS,h+22 target must equal observed consumption ex...
24,alignment_h23,0,PASS,h+23 target must equal observed consumption ex...
25,alignment_h24,0,PASS,h+24 target must equal observed consumption ex...

In [11]:
# Display the peak validation results from the results
results['peak_validation']

,check,violations,status,description
0,unique_peak_label_key,0,PASS,Diagnostic Peak labels must be unique by FSA +...
1,peak_label_binary,0,PASS,Peak-Risk labels must be binary when a thresho...
2,peak_threshold_availability_consistency,0,PASS,Available thresholds must produce a diagnostic...
3,walk_forward_threshold_no_future_year,0,PASS,Each diagnostic threshold must be fitted using...