# 08.09 — Modeling Foundation Summary

Execute the complete framework workflow and inspect the formal handoff to future model branches.

In [1]:
# Import libraries
from pathlib import Path
import sys

In [2]:
# Define the root directory of the project
PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

CONFIG_PATH = PROJECT_ROOT / "configs" / "modeling_foundation.yaml"
CONFIG_PATH

WindowsPath('e:/jcuenca/OneDrive - GUSCanada/5toTerm/01_Capstone/DataLocal/ontario-electricity-peak-risk/configs/modeling_foundation.yaml')

In [3]:
# Import module to manage modeling configuration, feature datasets, and directories
from src.ontario_peak_risk.modeling.common import (
    load_modeling_config,
    load_feature_dataset,
    ensure_modeling_directories,
)

In [4]:
# Load the modeling configuration, feature dataset, and ensure necessary directories exist
CONFIG, _ = load_modeling_config(CONFIG_PATH)
REPORTS_DIR, DOCS_DIR, OUTPUTS_DIR = ensure_modeling_directories(CONFIG, PROJECT_ROOT)
feature_dataset = load_feature_dataset(CONFIG, PROJECT_ROOT)
feature_dataset.shape

(262944, 100)

In [5]:
# Import the run_modeling_foundation function
from src.ontario_peak_risk.modeling.run_modeling_foundation import run_modeling_foundation

In [6]:
# Run the modeling foundation function and store the results
results = run_modeling_foundation(CONFIG_PATH)
results.keys()

Modeling Foundation Phase completed successfully.
Feature rows: 262,944
Complete Forecasting target rows: 262,800
Maximum forecast horizon: 24 hours
Forecasting selection metric: mae
Peak-Risk selection metric: pr_auc
Initial classification threshold: 0.5
Validation folds: 2
Final holdout: test_2025
Reports: E:\jcuenca\OneDrive - GUSCanada\5toTerm\01_Capstone\DataLocal\ontario-electricity-peak-risk\reports\modeling_foundation
Documentation: E:\jcuenca\OneDrive - GUSCanada\5toTerm\01_Capstone\DataLocal\ontario-electricity-peak-risk\docs\modeling_foundation

dict_keys(['feature_dataset', 'forecast_targets', 'validation_folds', 'final_holdout', 'split_summary', 'fsa_coverage', 'metric_dictionary', 'peak_horizon_policy', 'framework_validation', 'outputs_dir'])

In [7]:
# Display the split summary from the results
results["split_summary"]

,fold,role,configured_train_start,configured_train_end,safe_train_origin_end,train_rows,train_first_origin,train_last_origin,train_fsas,configured_evaluation_start,configured_evaluation_end,safe_evaluation_origin_end,evaluation_rows,evaluation_first_origin,evaluation_last_origin,evaluation_fsas,max_horizon_hours
0,fold_2023,validation,2021-01-01,2022-12-31 23:00:00,2022-12-30 23:00:00,104976,2021-01-01,2022-12-30 23:00:00,6,2023-01-01,2023-12-31 23:00:00,2023-12-30 23:00:00,52416,2023-01-01,2023-12-30 23:00:00,6,24
1,fold_2024,validation,2021-01-01,2023-12-31 23:00:00,2023-12-30 23:00:00,157536,2021-01-01,2023-12-30 23:00:00,6,2024-01-01,2024-12-31 23:00:00,2024-12-30 23:00:00,52560,2024-01-01,2024-12-30 23:00:00,6,24
2,test_2025,test,2021-01-01,2024-12-31 23:00:00,2024-12-30 23:00:00,210240,2021-01-01,2024-12-30 23:00:00,6,2025-01-01,2025-12-31 23:00:00,2025-12-30 23:00:00,52416,2025-01-01,2025-12-30 23:00:00,6,24

In [8]:
# Display the metric dictionary from the results
results["metric_dictionary"]

,task,metric,role,direction,description
0,forecasting,MAE,primary,lower_is_better,Mean absolute forecast error in kWh.
1,forecasting,RMSE,primary,lower_is_better,Root mean squared forecast error in kWh.
2,forecasting,MAPE,primary,lower_is_better,Mean absolute percentage error for non-zero de...
3,forecasting,WAPE,secondary,lower_is_better,Absolute error relative to total observed demand.
4,forecasting,Bias,secondary,closer_to_zero,Mean signed forecast error.
5,peak_risk,Precision,primary,higher_is_better,Share of predicted Peaks that are true Peaks.
6,peak_risk,Recall,primary,higher_is_better,Share of true Peaks correctly detected.
7,peak_risk,F1,primary,higher_is_better,Harmonic mean of Precision and Recall.
8,peak_risk,PR-AUC,primary,higher_is_better,Precision-Recall area; emphasized for class im...
9,peak_risk,ROC-AUC,secondary,higher_is_better,Area under the ROC curve.
10,peak_risk,Balanced Accuracy,secondary,higher_is_better,Average recall across both classes.

In [9]:
# Display the framework validation results from the results
results["framework_validation"]

,fold,role,check,status,details,latest_validation_end,test_start,configured_value
0,fold_2023,validation,non_empty_train,PASS,NaN,NaT,NaT,NaN
1,fold_2023,validation,non_empty_evaluation,PASS,NaN,NaT,NaT,NaN
2,fold_2023,validation,train_precedes_evaluation,PASS,NaN,NaT,NaT,NaN
3,fold_2023,validation,same_fsa_coverage,PASS,NaN,NaT,NaT,NaN
4,fold_2023,validation,no_temporal_overlap,PASS,NaN,NaT,NaT,NaN
5,fold_2023,validation,train_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
6,fold_2023,validation,evaluation_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
7,fold_2024,validation,non_empty_train,PASS,NaN,NaT,NaT,NaN
8,fold_2024,validation,non_empty_evaluation,PASS,NaN,NaT,NaT,NaN
9,fold_2024,validation,train_precedes_evaluation,PASS,NaN,NaT,NaT,NaN
10,fold_2024,validation,same_fsa_coverage,PASS,NaN,NaT,NaT,NaN
11,fold_2024,validation,no_temporal_overlap,PASS,NaN,NaT,NaT,NaN
12,fold_2024,validation,train_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
13,fold_2024,validation,evaluation_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
14,test_2025,test,non_empty_train,PASS,NaN,NaT,NaT,NaN
15,test_2025,test,non_empty_evaluation,PASS,NaN,NaT,NaT,NaN
16,test_2025,test,train_precedes_evaluation,PASS,NaN,NaT,NaT,NaN
17,test_2025,test,same_fsa_coverage,PASS,NaN,NaT,NaT,NaN
18,test_2025,test,no_temporal_overlap,PASS,NaN,NaT,NaT,NaN
19,test_2025,test,train_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
20,test_2025,test,evaluation_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
21,global,forecast_target,all_forecasting_target_columns_available,PASS,,NaT,NaT,NaN
22,fold_2023,validation,train_horizon_complete,PASS,,NaT,NaT,NaN
23,fold_2023,validation,evaluation_horizon_complete,PASS,,NaT,NaT,NaN
24,fold_2023,validation,train_h24_within_training_period,PASS,,NaT,NaT,NaN
25,fold_2023,validation,evaluation_h24_within_evaluation_period,PASS,,NaT,NaT,NaN
26,fold_2024,validation,train_horizon_complete,PASS,,NaT,NaT,NaN
27,fold_2024,validation,evaluation_horizon_complete,PASS,,NaT,NaT,NaN
28,fold_2024,validation,train_h24_within_training_period,PASS,,NaT,NaT,NaN
29,fold_2024,validation,evaluation_h24_within_evaluation_period,PASS,,NaT,NaT,NaN
30,test_2025,test,train_horizon_complete,PASS,,NaT,NaT,NaN
31,test_2025,test,evaluation_horizon_complete,PASS,,NaT,NaT,NaN
32,test_2025,test,train_h24_within_training_period,PASS,,NaT,NaT,NaN
33,test_2025,test,evaluation_h24_within_evaluation_period,PASS,,NaT,NaT,NaN
34,NaN,NaN,final_holdout_after_all_validation_periods,PASS,NaN,2024-12-31 23:00:00,2025-01-01,NaN
35,NaN,NaN,preprocessing_fit_scope_training_only,PASS,NaN,NaT,NaT,training_only
36,NaN,NaN,forecasting_selection_metric_is_primary,PASS,NaN,NaT,NaT,NaN
37,NaN,NaN,peak_selection_metric_is_primary,PASS,NaN,NaT,NaT,NaN
38,NaN,NaN,classification_probability_threshold_valid,PASS,NaN,NaT,NaT,NaN
39,NaN,NaN,forecast_and_peak_horizons_match,PASS,NaN,NaT,NaT,NaN

In [10]:
# Review FSA coverage
results["fsa_coverage"]

         fold        role  fsa  train_rows  evaluation_rows status
0   fold_2023  validation  L4T       17496             8736   PASS
1   fold_2023  validation  M5R       17496             8736   PASS
2   fold_2023  validation  M5S       17496             8736   PASS
3   fold_2023  validation  M6G       17496             8736   PASS
4   fold_2023  validation  M9R       17496             8736   PASS
5   fold_2023  validation  M9W       17496             8736   PASS
6   fold_2024  validation  L4T       26256             8760   PASS
7   fold_2024  validation  M5R       26256             8760   PASS
8   fold_2024  validation  M5S       26256             8760   PASS
9   fold_2024  validation  M6G       26256             8760   PASS
10  fold_2024  validation  M9R       26256             8760   PASS
11  fold_2024  validation  M9W       26256             8760   PASS
12  test_2025        test  L4T       35040             8736   PASS
13  test_2025        test  M5R       35040             8736   PASS
14  test_2025        test  M5S       35040             8736   PASS
15  test_2025        test  M6G       35040             8736   PASS
16  test_2025        test  M9R       35040             8736   PASS
17  test_2025        test  M9W       35040             8736   PASS

In [11]:
# Review Peak-Risk multi-horizon policy
results["peak_horizon_policy"]

,horizon,target,target_offset_hours,definition,threshold_scope
0,1,peak_h01,1,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
1,2,peak_h02,2,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
2,3,peak_h03,3,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
3,4,peak_h04,4,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
4,5,peak_h05,5,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
5,6,peak_h06,6,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
6,7,peak_h07,7,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
7,8,peak_h08,8,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
8,9,peak_h09,9,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
9,10,peak_h10,10,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
10,11,peak_h11,11,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
11,12,peak_h12,12,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
12,13,peak_h13,13,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
13,14,peak_h14,14,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
14,15,peak_h15,15,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
15,16,peak_h16,16,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
16,17,peak_h17,17,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
17,18,peak_h18,18,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
18,19,peak_h19,19,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
19,20,peak_h20,20,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
20,21,peak_h21,21,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
21,22,peak_h22,22,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
22,23,peak_h23,23,Peak status of the corresponding FSA at foreca...,training_only_fsa_season
23,24,peak_h24,24,Peak status of the corresponding FSA at foreca...,training_only_fsa_season

In [12]:
# Review all framework validation checks
results["framework_validation"]

,fold,role,check,status,details,latest_validation_end,test_start,configured_value
0,fold_2023,validation,non_empty_train,PASS,NaN,NaT,NaT,NaN
1,fold_2023,validation,non_empty_evaluation,PASS,NaN,NaT,NaT,NaN
2,fold_2023,validation,train_precedes_evaluation,PASS,NaN,NaT,NaT,NaN
3,fold_2023,validation,same_fsa_coverage,PASS,NaN,NaT,NaT,NaN
4,fold_2023,validation,no_temporal_overlap,PASS,NaN,NaT,NaT,NaN
5,fold_2023,validation,train_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
6,fold_2023,validation,evaluation_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
7,fold_2024,validation,non_empty_train,PASS,NaN,NaT,NaT,NaN
8,fold_2024,validation,non_empty_evaluation,PASS,NaN,NaT,NaT,NaN
9,fold_2024,validation,train_precedes_evaluation,PASS,NaN,NaT,NaT,NaN
10,fold_2024,validation,same_fsa_coverage,PASS,NaN,NaT,NaT,NaN
11,fold_2024,validation,no_temporal_overlap,PASS,NaN,NaT,NaT,NaN
12,fold_2024,validation,train_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
13,fold_2024,validation,evaluation_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
14,test_2025,test,non_empty_train,PASS,NaN,NaT,NaT,NaN
15,test_2025,test,non_empty_evaluation,PASS,NaN,NaT,NaT,NaN
16,test_2025,test,train_precedes_evaluation,PASS,NaN,NaT,NaT,NaN
17,test_2025,test,same_fsa_coverage,PASS,NaN,NaT,NaT,NaN
18,test_2025,test,no_temporal_overlap,PASS,NaN,NaT,NaT,NaN
19,test_2025,test,train_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
20,test_2025,test,evaluation_origin_is_horizon_safe,PASS,NaN,NaT,NaT,NaN
21,global,forecast_target,all_forecasting_target_columns_available,PASS,,NaT,NaT,NaN
22,fold_2023,validation,train_horizon_complete,PASS,,NaT,NaT,NaN
23,fold_2023,validation,evaluation_horizon_complete,PASS,,NaT,NaT,NaN
24,fold_2023,validation,train_h24_within_training_period,PASS,,NaT,NaT,NaN
25,fold_2023,validation,evaluation_h24_within_evaluation_period,PASS,,NaT,NaT,NaN
26,fold_2024,validation,train_horizon_complete,PASS,,NaT,NaT,NaN
27,fold_2024,validation,evaluation_horizon_complete,PASS,,NaT,NaT,NaN
28,fold_2024,validation,train_h24_within_training_period,PASS,,NaT,NaT,NaN
29,fold_2024,validation,evaluation_h24_within_evaluation_period,PASS,,NaT,NaT,NaN
30,test_2025,test,train_horizon_complete,PASS,,NaT,NaT,NaN
31,test_2025,test,evaluation_horizon_complete,PASS,,NaT,NaT,NaN
32,test_2025,test,train_h24_within_training_period,PASS,,NaT,NaT,NaN
33,test_2025,test,evaluation_h24_within_evaluation_period,PASS,,NaT,NaT,NaN
34,NaN,NaN,final_holdout_after_all_validation_periods,PASS,NaN,2024-12-31 23:00:00,2025-01-01,NaN
35,NaN,NaN,preprocessing_fit_scope_training_only,PASS,NaN,NaT,NaT,training_only
36,NaN,NaN,forecasting_selection_metric_is_primary,PASS,NaN,NaT,NaT,NaN
37,NaN,NaN,peak_selection_metric_is_primary,PASS,NaN,NaT,NaT,NaN
38,NaN,NaN,classification_probability_threshold_valid,PASS,NaN,NaT,NaT,NaN
39,NaN,NaN,forecast_and_peak_horizons_match,PASS,NaN,NaT,NaT,NaN

In [13]:
# Final validation
validation_ok = (
    results[
        "framework_validation"
    ]["status"]
    .eq("PASS")
    .all()
)

fsa_coverage_ok = (
    results[
        "fsa_coverage"
    ]["status"]
    .eq("PASS")
    .all()
)

assert validation_ok, (
    "Framework validation contains FAIL checks."
)

assert fsa_coverage_ok, (
    "At least one FSA has insufficient fold coverage."
)

print(
    "Modeling Foundation is ready for final review."
)

Modeling Foundation is ready for final review.