# 01_01 - Data Loading Check

In [1]:
import pandas as pd
from pathlib import Path

DATA_DIR = Path.cwd().parents[1] / "data" / "processed"
DATA_DIR

WindowsPath('C:/Tessy/Master of Data Analytics/TERM V/ontario-electricity-peak-risk/data/processed')

## 1. Calendar

One row per hour, with date and time features already built in (season, weekday, holiday flags, cyclical encodings). Join key: `timestamp_local`, a fixed-clock timestamp with no daylight saving shifts.

In [2]:
calendar_df = pd.read_csv(DATA_DIR / "calendar_hourly_ontario_timestamp.csv")

print("shape:", calendar_df.shape)
calendar_df.info()

shape: (52584, 45)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52584 entries, 0 to 52583
Data columns (total 45 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   timestamp_utc            52584 non-null  object
 1   timestamp_local          52584 non-null  object
 2   timestamp_toronto        52584 non-null  object
 3   date                     52584 non-null  object
 4   year                     52584 non-null  int64
 5   quarter                  52584 non-null  int64
 6   month                    52584 non-null  int64
 7   month_name               52584 non-null  object
 8   week_of_year             52584 non-null  int64
 9   day_of_year              52584 non-null  int64
 10  day_of_month             52584 non-null  int64
 11  hour                     52584 non-null  int64
 12  hour_group               52584 non-null  object
 13  weekday                  52584 non-null  int64
 14  weekday_name             52584 non-null  object
 15  is_weekend               52584 non-null  int64
 16  is_workday               52584 non-null  int64
 17  is_monday                52584 non-null  int64
 18  is_friday                52584 non-null  int64
 19  season                   52584 non-null  object
 20  is_business_hour         52584 non-null  int64
 21  is_peak_hour_window      52584 non-null  int64
 22  is_month_start           52584 non-null  int64
 23  is_month_end             52584 non-null  int64
 24  is_year_start            52584 non-null  int64
 25  is_year_end              52584 non-null  int64
 26  is_public_holiday        52584 non-null  int64
 27  holiday_name             1416 non-null   object
 28  is_day_before_holiday    52584 non-null  int64
 29  is_day_after_holiday     52584 non-null  int64
 30  days_to_holiday          52584 non-null  int64
 31  days_after_holiday       52584 non-null  int64
 32  is_long_weekend          52584 non-null  int64
 33  is_daylight_saving_time  52584 non-null  int64
 34  is_dst_transition_day    52584 non-null  int64
 35  is_spring_forward_day    52584 non-null  int64
 36  is_fall_back_day         52584 non-null  int64
 37  utc_offset_hours         52584 non-null  int64
 38  date_index               52584 non-null  int64
 39  hour_sin                 52584 non-null  float64
 40  hour_cos                 52584 non-null  float64
 41  weekday_sin              52584 non-null  float64
 42  weekday_cos              52584 non-null  float64
 43  month_sin                52584 non-null  float64
 44  month_cos                52584 non-null  float64
dtypes: float64(6), int64(30), object(9)
memory usage: 18.1+ MB

In [3]:
calendar_df.head()

,timestamp_utc,timestamp_local,timestamp_toronto,date,year,quarter,month,month_name,week_of_year,day_of_year,...,is_spring_forward_day,is_fall_back_day,utc_offset_hours,date_index,hour_sin,hour_cos,weekday_sin,weekday_cos,month_sin,month_cos
0,2021-01-01 05:00:00+00:00,2021-01-01 00:00:00,2021-01-01 00:00:00-05:00,2021-01-01,2021,1,1,January,53,1,...,0,0,-5,0,0.000000,1.000000,-0.433884,-0.900969,0.0,1.0
1,2021-01-01 06:00:00+00:00,2021-01-01 01:00:00,2021-01-01 01:00:00-05:00,2021-01-01,2021,1,1,January,53,1,...,0,0,-5,0,0.258819,0.965926,-0.433884,-0.900969,0.0,1.0
2,2021-01-01 07:00:00+00:00,2021-01-01 02:00:00,2021-01-01 02:00:00-05:00,2021-01-01,2021,1,1,January,53,1,...,0,0,-5,0,0.500000,0.866025,-0.433884,-0.900969,0.0,1.0
3,2021-01-01 08:00:00+00:00,2021-01-01 03:00:00,2021-01-01 03:00:00-05:00,2021-01-01,2021,1,1,January,53,1,...,0,0,-5,0,0.707107,0.707107,-0.433884,-0.900969,0.0,1.0
4,2021-01-01 09:00:00+00:00,2021-01-01 04:00:00,2021-01-01 04:00:00-05:00,2021-01-01,2021,1,1,January,53,1,...,0,0,-5,0,0.866025,0.500000,-0.433884,-0.900969,0.0,1.0

## 2. Weather - Toronto City

Covers the downtown FSAs (M5S, M5R, M6G). Reports temperature, humidity and precipitation, not wind speed or visibility. Join key: `Date/Time (LST)`.

In [4]:
weather_city_df = pd.read_csv(DATA_DIR / "weather_toronto_city_6158355.csv")

print("shape:", weather_city_df.shape)
weather_city_df.info()

shape: (52584, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52584 entries, 0 to 52583
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Longitude (x)        52584 non-null  float64
 1   Latitude (y)         52584 non-null  float64
 2   Station Name         52584 non-null  object
 3   Climate ID           52584 non-null  int64
 4   Date/Time (LST)      52584 non-null  object
 5   Year                 52584 non-null  int64
 6   Month                52584 non-null  int64
 7   Day                  52584 non-null  int64
 8   Time (LST)           52584 non-null  object
 9   Flag                 0 non-null      float64
 10  Temp (°C)            48794 non-null  float64
 11  Temp Flag            0 non-null      float64
 12  Dew Point Temp (°C)  48794 non-null  float64
 13  Dew Point Temp Flag  0 non-null      float64
 14  Rel Hum (%)          48794 non-null  float64
 15  Rel Hum Flag         0 non-null      float64
 16  Precip. Amount (mm)  48794 non-null  float64
 17  Precip. Amount Flag  0 non-null      float64
 18  Wind Dir (10s deg)   0 non-null      float64
 19  Wind Dir Flag        0 non-null      float64
 20  Wind Spd (km/h)      0 non-null      float64
 21  Wind Spd Flag        0 non-null      float64
 22  Visibility (km)      0 non-null      float64
 23  Visibility Flag      0 non-null      float64
 24  Stn Press (kPa)      48794 non-null  float64
 25  Stn Press Flag       0 non-null      float64
 26  Hmdx                 8575 non-null   float64
 27  Hmdx Flag            0 non-null      float64
 28  Wind Chill           0 non-null      float64
 29  Wind Chill Flag      0 non-null      float64
 30  Weather              0 non-null      float64
 31  SOURCE_FILE          52584 non-null  object
 32  SOURCE_PERIOD        52584 non-null  int64
dtypes: float64(24), int64(5), object(4)
memory usage: 13.2+ MB

In [5]:
weather_city_df.head()

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time (LST),Year,Month,Day,Time (LST),Flag,...,Visibility Flag,Stn Press (kPa),Stn Press Flag,Hmdx,Hmdx Flag,Wind Chill,Wind Chill Flag,Weather,SOURCE_FILE,SOURCE_PERIOD
0,-79.4,43.67,TORONTO CITY,6158355,2021-01-01 00:00:00,2021,1,1,00:00,NaN,...,NaN,101.67,NaN,NaN,NaN,NaN,NaN,NaN,2021_01.csv,202101
1,-79.4,43.67,TORONTO CITY,6158355,2021-01-01 01:00:00,2021,1,1,01:00,NaN,...,NaN,101.66,NaN,NaN,NaN,NaN,NaN,NaN,2021_01.csv,202101
2,-79.4,43.67,TORONTO CITY,6158355,2021-01-01 02:00:00,2021,1,1,02:00,NaN,...,NaN,101.69,NaN,NaN,NaN,NaN,NaN,NaN,2021_01.csv,202101
3,-79.4,43.67,TORONTO CITY,6158355,2021-01-01 03:00:00,2021,1,1,03:00,NaN,...,NaN,101.77,NaN,NaN,NaN,NaN,NaN,NaN,2021_01.csv,202101
4,-79.4,43.67,TORONTO CITY,6158355,2021-01-01 04:00:00,2021,1,1,04:00,NaN,...,NaN,101.75,NaN,NaN,NaN,NaN,NaN,NaN,2021_01.csv,202101

## 3. Weather - Toronto INTL A (Pearson)

Covers the airport-area FSAs (L4T, M9W, M9R). Reports wind speed and visibility, not precipitation. Join key: `Date/Time (LST)`.

In [6]:
weather_intl_df = pd.read_csv(DATA_DIR / "weather_toronto_intl_a_6158731.csv")

print("shape:", weather_intl_df.shape)
weather_intl_df.info()

shape: (52584, 33)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52584 entries, 0 to 52583
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Longitude (x)        52584 non-null  float64
 1   Latitude (y)         52584 non-null  float64
 2   Station Name         52584 non-null  object
 3   Climate ID           52584 non-null  int64
 4   Date/Time (LST)      52584 non-null  object
 5   Year                 52584 non-null  int64
 6   Month                52584 non-null  int64
 7   Day                  52584 non-null  int64
 8   Time (LST)           52584 non-null  object
 9   Flag                 0 non-null      float64
 10  Temp (°C)            48786 non-null  float64
 11  Temp Flag            0 non-null      float64
 12  Dew Point Temp (°C)  48785 non-null  float64
 13  Dew Point Temp Flag  1 non-null      object
 14  Rel Hum (%)          48785 non-null  float64
 15  Rel Hum Flag         1 non-null      object
 16  Precip. Amount (mm)  0 non-null      float64
 17  Precip. Amount Flag  0 non-null      float64
 18  Wind Dir (10s deg)   47945 non-null  float64
 19  Wind Dir Flag        0 non-null      float64
 20  Wind Spd (km/h)      48786 non-null  float64
 21  Wind Spd Flag        0 non-null      float64
 22  Visibility (km)      48785 non-null  float64
 23  Visibility Flag      1 non-null      object
 24  Stn Press (kPa)      48786 non-null  float64
 25  Stn Press Flag       0 non-null      float64
 26  Hmdx                 8489 non-null   float64
 27  Hmdx Flag            0 non-null      float64
 28  Wind Chill           10162 non-null  float64
 29  Wind Chill Flag      0 non-null      float64
 30  Weather              20943 non-null  object
 31  SOURCE_FILE          52584 non-null  object
 32  SOURCE_PERIOD        52584 non-null  int64
dtypes: float64(20), int64(5), object(8)
memory usage: 13.2+ MB

C:\Users\tessy\AppData\Local\Temp\ipykernel_12348\518485187.py:1: DtypeWarning: Columns (13,15,23,30) have mixed types. Specify dtype option on import or set low_memory=False.
  weather_intl_df = pd.read_csv(DATA_DIR / "weather_toronto_intl_a_6158731.csv")

In [7]:
weather_intl_df.head()

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time (LST),Year,Month,Day,Time (LST),Flag,...,Visibility Flag,Stn Press (kPa),Stn Press Flag,Hmdx,Hmdx Flag,Wind Chill,Wind Chill Flag,Weather,SOURCE_FILE,SOURCE_PERIOD
0,-79.63,43.68,TORONTO INTL A,6158731,2021-01-01 00:00:00,2021,1,1,00:00,NaN,...,NaN,100.93,NaN,NaN,NaN,-4.0,NaN,NaN,2021_01.csv,202101
1,-79.63,43.68,TORONTO INTL A,6158731,2021-01-01 01:00:00,2021,1,1,01:00,NaN,...,NaN,100.93,NaN,NaN,NaN,-3.0,NaN,Clear,2021_01.csv,202101
2,-79.63,43.68,TORONTO INTL A,6158731,2021-01-01 02:00:00,2021,1,1,02:00,NaN,...,NaN,100.95,NaN,NaN,NaN,-4.0,NaN,NaN,2021_01.csv,202101
3,-79.63,43.68,TORONTO INTL A,6158731,2021-01-01 03:00:00,2021,1,1,03:00,NaN,...,NaN,101.03,NaN,NaN,NaN,-5.0,NaN,NaN,2021_01.csv,202101
4,-79.63,43.68,TORONTO INTL A,6158731,2021-01-01 04:00:00,2021,1,1,04:00,NaN,...,NaN,101.02,NaN,NaN,NaN,-5.0,NaN,Mostly Cloudy,2021_01.csv,202101

## 4. Hourly Consumption per FSA (6 files)

One file per FSA, join key `TIMESTAMP`. Unlike calendar and weather, this is not one row per hour: it is one row per (FSA, hour, customer type, price plan), so the same hour appears multiple times, split across customer segments.

In [8]:
FSAS = ["l4t", "m5r", "m5s", "m6g", "m9r", "m9w"]

consumption_dfs = {}
load_summary = []
for fsa in FSAS:
    df = pd.read_csv(DATA_DIR / f"hourly_consumption_fsa_{fsa}.csv")
    consumption_dfs[fsa.upper()] = df
    load_summary.append({"FSA": fsa.upper(), "rows": df.shape[0], "cols": df.shape[1], "FSA values": df["FSA"].unique()})

pd.DataFrame(load_summary)

   FSA    rows  cols FSA values
0  L4T  215697    11      [L4T]
1  M5R  101596    11      [M5R]
2  M5S  103032    11      [M5S]
3  M6G  203915    11      [M6G]
4  M9R  209729    11      [M9R]
5  M9W  212492    11      [M9W]

In [9]:
# Using M5S as a representative sample - all six files share the same structure
consumption_dfs["M5S"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103032 entries, 0 to 103031
Data columns (total 11 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   FSA                       103032 non-null  object
 1   DATE                      103032 non-null  object
 2   HOUR                      103032 non-null  int64
 3   CUSTOMER_TYPE             103032 non-null  object
 4   PRICE_PLAN                103032 non-null  object
 5   TOTAL_CONSUMPTION         103032 non-null  float64
 6   PREMISE_COUNT             103032 non-null  int64
 7   SOURCE_PERIOD             103032 non-null  int64
 8   INTERVAL_START_TIMESTAMP  103032 non-null  object
 9   INTERVAL_END_TIMESTAMP    103032 non-null  object
 10  TIMESTAMP                 103032 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 8.6+ MB

In [10]:
consumption_dfs["M5S"].head()

,FSA,DATE,HOUR,CUSTOMER_TYPE,PRICE_PLAN,TOTAL_CONSUMPTION,PREMISE_COUNT,SOURCE_PERIOD,INTERVAL_START_TIMESTAMP,INTERVAL_END_TIMESTAMP,TIMESTAMP
0,M5S,2021-01-01 00:00:00,1,Residential,TOU,4011.1,5625,202101,2021-01-01 00:00:00,2021-01-01 01:00:00,2021-01-01 00:00:00
1,M5S,2021-01-01 00:00:00,1,Residential,Tiered,175.1,302,202101,2021-01-01 00:00:00,2021-01-01 01:00:00,2021-01-01 00:00:00
2,M5S,2021-01-01 00:00:00,2,Residential,TOU,3712.7,5625,202101,2021-01-01 01:00:00,2021-01-01 02:00:00,2021-01-01 01:00:00
3,M5S,2021-01-01 00:00:00,2,Residential,Tiered,156.1,302,202101,2021-01-01 01:00:00,2021-01-01 02:00:00,2021-01-01 01:00:00
4,M5S,2021-01-01 00:00:00,3,Residential,TOU,3504.1,5625,202101,2021-01-01 02:00:00,2021-01-01 03:00:00,2021-01-01 02:00:00

## 5. Comparing the datasets side by side

This section looks at how the files relate to each other: whether they cover the same period of time, and how much of the row count in the consumption files comes from real hourly variation versus the customer-type/price-plan split.

In [11]:
date_ranges = [
    {"dataset": "calendar", "min": calendar_df["timestamp_local"].min(), "max": calendar_df["timestamp_local"].max()},
    {"dataset": "weather_toronto_city", "min": weather_city_df["Date/Time (LST)"].min(), "max": weather_city_df["Date/Time (LST)"].max()},
    {"dataset": "weather_toronto_intl_a", "min": weather_intl_df["Date/Time (LST)"].min(), "max": weather_intl_df["Date/Time (LST)"].max()},
]
date_ranges += [
    {"dataset": f"consumption_{fsa}", "min": df["TIMESTAMP"].min(), "max": df["TIMESTAMP"].max()}
    for fsa, df in consumption_dfs.items()
]

pd.DataFrame(date_ranges)

                  dataset                  min                  max
0                calendar  2021-01-01 00:00:00  2026-12-31 23:00:00
1    weather_toronto_city  2021-01-01 00:00:00  2026-12-31 23:00:00
2  weather_toronto_intl_a  2021-01-01 00:00:00  2026-12-31 23:00:00
3         consumption_L4T  2021-01-01 00:00:00  2025-12-31 23:00:00
4         consumption_M5R  2021-01-01 00:00:00  2025-12-31 23:00:00
5         consumption_M5S  2021-01-01 00:00:00  2025-12-31 23:00:00
6         consumption_M6G  2021-01-01 00:00:00  2025-12-31 23:00:00
7         consumption_M9R  2021-01-01 00:00:00  2025-12-31 23:00:00
8         consumption_M9W  2021-01-01 00:00:00  2025-12-31 23:00:00

The calendar and weather files run through the end of 2026, while consumption stops at the end of 2025. The smart-meter readings simply have not been produced for those later dates yet. Since consumption defines what can actually be modeled, 2021-2025 is the real usable window, and the 2026 rows in calendar and weather need to be left out once everything is joined.

In [ ]:
# CUSTOMER_TYPE / PRICE_PLAN combinations per FSA, explains why there are multiple rows per FSA-hour
combos_by_fsa = pd.concat(
    [
        df[["CUSTOMER_TYPE", "PRICE_PLAN"]].drop_duplicates().assign(FSA=fsa)
        for fsa, df in consumption_dfs.items()
    ],
    ignore_index=True,
)[["FSA", "CUSTOMER_TYPE", "PRICE_PLAN"]].sort_values(["FSA", "CUSTOMER_TYPE", "PRICE_PLAN"])

combos_by_fsa

In [13]:
# Final summary: shape of each raw dataset
summary = {
    "calendar": calendar_df.shape,
    "weather_toronto_city": weather_city_df.shape,
    "weather_toronto_intl_a": weather_intl_df.shape,
    **{f"consumption_{fsa}": df.shape for fsa, df in consumption_dfs.items()},
}
pd.Series(summary, name="shape (rows, cols)")

calendar                   (52584, 45)
weather_toronto_city       (52584, 33)
weather_toronto_intl_a     (52584, 33)
consumption_L4T           (215697, 11)
consumption_M5R           (101596, 11)
consumption_M5S           (103032, 11)
consumption_M6G           (203915, 11)
consumption_M9R           (209729, 11)
consumption_M9W           (212492, 11)
Name: shape (rows, cols), dtype: object

The combination counts above explain the row-count gap seen earlier between, for example, M5R (about 101K rows) and L4T (about 216K rows): every FSA is still one row per hour, just multiplied by however many customer-type/price-plan segments exist for that FSA. This needs to be collapsed to a single row per FSA-hour before the data can be used for modeling.