# IFB 00 — Design & Input Contract

Define what the operational system supplies and what the IFB calculates automatically.

In [1]:
# Import libraries
from pathlib import Path
import sys
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Define config paths
PROJECT_ROOT = Path.cwd()
while (
    not (PROJECT_ROOT / "src").exists()
    and PROJECT_ROOT != PROJECT_ROOT.parent
):
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

CONFIG_PATH = (
    PROJECT_ROOT
    / "configs"
    / "inference_feature_builder.yaml"
)

print("Project root:", PROJECT_ROOT)
print("IFB config:", CONFIG_PATH)

Project root: e:\jcuenca\OneDrive - GUSCanada\5toTerm\01_Capstone\DataLocal\ontario-electricity-peak-risk
IFB config: e:\jcuenca\OneDrive - GUSCanada\5toTerm\01_Capstone\DataLocal\ontario-electricity-peak-risk\configs\inference_feature_builder.yaml


The external user/system supplies recent observed demand, optional recent
observed weather, an h0...h24 weather forecast, a forecast origin and the
requested FSAs. The user does **not** supply lags, rolling statistics or
calendar encodings.

The current frozen models use weather/context at the forecast origin. Future
weather h+1...h+24 is still accepted because it is required for the later
scenario-analysis/application layer.

In [3]:
# Import module for running inference_feature_builder
from src.ontario_peak_risk.inference_feature_builder.io import (
    load_ifb_config,
    resolve_path,
)
from src.ontario_peak_risk.inference_feature_builder.builder import (
    load_model_contracts,
    expected_features,
)

In [4]:
# Recovery configs
config, project_root = load_ifb_config(CONFIG_PATH)
artifacts = resolve_path(project_root, config["paths"]["artifacts_dir"])
contracts = load_model_contracts(artifacts)

In [5]:
# Display Random Forest frozen feature contract
print("Random Forest frozen feature contract")
display(pd.DataFrame({"feature": expected_features(contracts["rf"])}))

Random Forest frozen feature contract

                           feature
0                      target_hour
1                   target_weekday
2                     target_month
3                target_is_weekend
4                  target_hour_sin
5                  target_hour_cos
6               target_weekday_sin
7               target_weekday_cos
8                 target_month_sin
9                 target_month_cos
10                  target_lag_24h
11                  target_lag_48h
12                 target_lag_168h
13         origin_rolling_mean_24h
14          origin_rolling_std_24h
15        origin_rolling_mean_168h
16               origin__Temp (°C)
17             origin__Rel Hum (%)
18         origin__Stn Press (kPa)
19  origin__reported_premise_count
20                             fsa
21                   target_season

In [6]:
# Display XGBoost frozen feature contract
print("XGBoost frozen feature contract")
display(pd.DataFrame({"feature": expected_features(contracts["xgb"])}))

XGBoost frozen feature contract

                           feature
0                      target_hour
1                   target_weekday
2                     target_month
3                target_is_weekend
4                  target_hour_sin
5                  target_hour_cos
6               target_weekday_sin
7               target_weekday_cos
8                 target_month_sin
9                 target_month_cos
10                  target_lag_24h
11                  target_lag_48h
12                 target_lag_168h
13         origin_rolling_mean_24h
14          origin_rolling_std_24h
15        origin_rolling_mean_168h
16               origin__Temp (°C)
17             origin__Rel Hum (%)
18         origin__Stn Press (kPa)
19  origin__reported_premise_count
20                             fsa
21                   target_season