# IP 02 — Integrated Prediction Template

Run this after the future inference-feature builder has prepared a model-compatible feature dataset.

In [1]:
# Import libraries
from pathlib import Path
import sys
import json
import yaml
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# Define config paths
PROJECT_ROOT = Path.cwd()
while (
    not (PROJECT_ROOT / "src").exists()
    and PROJECT_ROOT != PROJECT_ROOT.parent
):
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

CONFIG_PATH = (PROJECT_ROOT / "configs" / "integrated_pipeline.yaml")

with CONFIG_PATH.open("r", encoding="utf-8") as handle:
    CONFIG = yaml.safe_load(handle)

CONFIG_PATH

WindowsPath('e:/jcuenca/OneDrive - GUSCanada/5toTerm/01_Capstone/DataLocal/ontario-electricity-peak-risk/configs/integrated_pipeline.yaml')

In [3]:
# Import module for running Integrated Pipeline
from src.ontario_peak_risk.modeling.common import (
    load_feature_dataset,
    load_modeling_config,
)

from src.ontario_peak_risk.inference.integrated_pipeline import (
    IntegratedPredictionPipeline,
    save_prediction_outputs,
)

In [4]:
FOUNDATION_PATH = (
    PROJECT_ROOT
    / "configs"
    / "modeling_foundation.yaml"
)

modeling_config, _ = load_modeling_config(
    FOUNDATION_PATH
)

feature_dataset = load_feature_dataset(
    modeling_config,
    PROJECT_ROOT,
)

feature_dataset["timestamp"] = pd.to_datetime(
    feature_dataset["timestamp"]
)

print("Feature dataset:", feature_dataset.shape)
print(
    "Available period:",
    feature_dataset["timestamp"].min(),
    "to",
    feature_dataset["timestamp"].max(),
)
print(
    "FSAs:",
    sorted(feature_dataset["fsa"].dropna().unique().tolist()),
)

Feature dataset: (262944, 100)
Available period: 2021-01-01 00:00:00 to 2025-12-31 23:00:00
FSAs: ['L4T', 'M5R', 'M5S', 'M6G', 'M9R', 'M9W']

In [5]:
# ------------------------------------------------------------
# Historical replay forecast origin
# ------------------------------------------------------------
# This is a pipeline smoke test, NOT another model evaluation.
# We choose the latest timestamp that still has a complete
# 24-hour feature window in the historical feature dataset.

available_fsas = sorted(
    feature_dataset["fsa"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)

max_timestamp = feature_dataset["timestamp"].max()

forecast_origin = (
    max_timestamp
    - pd.Timedelta(hours=24)
)

# Prefer an exact timestamp present for all FSAs.
candidate_origins = (
    feature_dataset.loc[
        feature_dataset["timestamp"] <= forecast_origin,
        ["fsa", "timestamp"],
    ]
    .groupby("timestamp", observed=True)["fsa"]
    .nunique()
)

candidate_origins = candidate_origins[
    candidate_origins >= len(available_fsas)
]

if candidate_origins.empty:
    raise ValueError(
        "Could not find a historical replay origin with all FSAs available."
    )

forecast_origin = candidate_origins.index.max()

print("Historical replay forecast origin:", forecast_origin)
print("FSAs:", available_fsas)

Historical replay forecast origin: 2025-12-30 23:00:00
FSAs: ['L4T', 'M5R', 'M5S', 'M6G', 'M9R', 'M9W']

In [6]:
# Defin artifacts
ARTIFACTS = (
    PROJECT_ROOT
    / CONFIG["paths"]["artifacts_dir"]
)

#Load pipeline
pipeline = IntegratedPredictionPipeline(
    ARTIFACTS
)


# Example only:
# inference_feature_dataset = ...
# output = pipeline.predict(
#     forecast_origin="2026-01-15 00:00:00",
#     fsas=["L4T", "M5R", "M5S", "M6G", "M9R", "M9W"],
#     inference_feature_dataset=inference_feature_dataset,
# )
# display(output.head(30))

output = pipeline.predict(
    forecast_origin=forecast_origin,
    fsas=available_fsas,
    inference_feature_dataset=feature_dataset,
)

display(output.head(30))

,fsa,forecast_origin,target_timestamp,horizon,forecast_consumption_kwh,peak_risk_score,peak_alert
0,L4T,2025-12-30 23:00:00,2025-12-31 00:00:00,1,11391.804060,0.000132,False
1,L4T,2025-12-30 23:00:00,2025-12-31 01:00:00,2,10575.189247,0.000073,False
2,L4T,2025-12-30 23:00:00,2025-12-31 02:00:00,3,9967.082221,0.000057,False
3,L4T,2025-12-30 23:00:00,2025-12-31 03:00:00,4,9662.285006,0.000113,False
4,L4T,2025-12-30 23:00:00,2025-12-31 04:00:00,5,9579.000471,0.000128,False
5,L4T,2025-12-30 23:00:00,2025-12-31 05:00:00,6,9780.371439,0.000157,False
6,L4T,2025-12-30 23:00:00,2025-12-31 06:00:00,7,9966.185314,0.000100,False
7,L4T,2025-12-30 23:00:00,2025-12-31 07:00:00,8,10458.347517,0.000066,False
8,L4T,2025-12-30 23:00:00,2025-12-31 08:00:00,9,11145.486643,0.000220,False
9,L4T,2025-12-30 23:00:00,2025-12-31 09:00:00,10,11855.571180,0.000246,False
10,L4T,2025-12-30 23:00:00,2025-12-31 10:00:00,11,12391.404721,0.000842,False
11,L4T,2025-12-30 23:00:00,2025-12-31 11:00:00,12,12932.315236,0.003967,False
12,L4T,2025-12-30 23:00:00,2025-12-31 12:00:00,13,13217.549967,0.006139,False
13,L4T,2025-12-30 23:00:00,2025-12-31 13:00:00,14,13363.075382,0.009013,False
14,L4T,2025-12-30 23:00:00,2025-12-31 14:00:00,15,13323.211585,0.008334,False
15,L4T,2025-12-30 23:00:00,2025-12-31 15:00:00,16,13413.202431,0.003882,False
16,L4T,2025-12-30 23:00:00,2025-12-31 16:00:00,17,13815.369288,0.060568,True
17,L4T,2025-12-30 23:00:00,2025-12-31 17:00:00,18,14528.283205,0.199193,True
18,L4T,2025-12-30 23:00:00,2025-12-31 18:00:00,19,14755.807193,0.198429,True
19,L4T,2025-12-30 23:00:00,2025-12-31 19:00:00,20,14865.533818,0.415957,True
20,L4T,2025-12-30 23:00:00,2025-12-31 20:00:00,21,14765.034672,0.204712,True
21,L4T,2025-12-30 23:00:00,2025-12-31 21:00:00,22,14284.078835,0.098416,True
22,L4T,2025-12-30 23:00:00,2025-12-31 22:00:00,23,13374.042893,0.013436,False
23,L4T,2025-12-30 23:00:00,2025-12-31 23:00:00,24,12422.134481,0.002616,False
24,M5R,2025-12-30 23:00:00,2025-12-31 00:00:00,1,10069.108337,0.001954,False
25,M5R,2025-12-30 23:00:00,2025-12-31 01:00:00,2,9709.388217,0.001427,False
26,M5R,2025-12-30 23:00:00,2025-12-31 02:00:00,3,9570.400647,0.001290,False
27,M5R,2025-12-30 23:00:00,2025-12-31 03:00:00,4,9469.959666,0.001082,False
28,M5R,2025-12-30 23:00:00,2025-12-31 04:00:00,5,9404.949297,0.001383,False
29,M5R,2025-12-30 23:00:00,2025-12-31 05:00:00,6,9555.515192,0.001800,False

In [7]:
# Display pipeline
pipeline

In [8]:
print("Rows:", len(output))
print("Expected rows:", len(available_fsas) * 24)
print("Horizons:", output["horizon"].min(), "to", output["horizon"].max())
print("FSA count:", output["fsa"].nunique())
print("Peak alerts:", int(output["peak_alert"].sum()))

Rows: 144
Expected rows: 144
Horizons: 1 to 24
FSA count: 6
Peak alerts: 50

In [9]:
OUTPUT_DIR = (
    PROJECT_ROOT
    / CONFIG["paths"]["outputs_dir"]
    / "historical_replay_demo"
)

save_prediction_outputs(
    output,
    OUTPUT_DIR,
)

summary = (
    output
    .groupby("fsa", observed=True)
    .agg(
        max_forecast_consumption_kwh=(
            "forecast_consumption_kwh",
            "max",
        ),
        max_peak_risk_score=(
            "peak_risk_score",
            "max",
        ),
        peak_alert_hours=(
            "peak_alert",
            "sum",
        ),
    )
    .reset_index()
)

summary.to_csv(
    OUTPUT_DIR / "integrated_24h_summary_by_fsa.csv",
    index=False,
)

display(summary)

print("Saved outputs to:", OUTPUT_DIR)

   fsa  max_forecast_consumption_kwh  max_peak_risk_score  peak_alert_hours
0  L4T                  14865.533818             0.415957                 6
1  M5R                  13135.196049             0.988430                12
2  M5S                   6963.333033             0.991410                11
3  M6G                  17741.693093             0.951889                 6
4  M9R                   8212.401477             0.960627                 7
5  M9W                  18804.563871             0.971639                 8

Saved outputs to: e:\jcuenca\OneDrive - GUSCanada\5toTerm\01_Capstone\DataLocal\ontario-electricity-peak-risk\outputs\integrated_pipeline\historical_replay_demo

### Interpretation

This is a **historical replay / smoke test** to demonstrate that the 48 serialized model artifacts can be loaded and executed through a single logical pipeline. It is not a new holdout evaluation and should not be used to change model parameters.